# Generated by Django 3.1.3 on 2020-11-06 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('open_date', models.DateTimeField()),
                ('close_date', models.DateTimeField()),
                ('exp_date', models.DateTimeField()),
                ('longshort', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', max_length=5)),
                ('callput', models.CharField(choices=[('call', 'Call'), ('put', 'Put')], default='call', max_length=4)),
                ('strike', models.DecimalField(decimal_places=2, max_digits=4)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=4)),
                ('count', models.PositiveSmallIntegerField()),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=4)),
                ('account', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('open', 'Open'), ('exercised', 'Exercised')], default='open', max_length=9)),
            ],
        ),
    ]
