# Generated by Django 3.1.3 on 2020-11-06 04:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategies', '0003_auto_20201105_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='Brokerage',
        ),
        migrations.RenameField(
            model_name='basicoption',
            old_name='account',
            new_name='brokerage',
        ),
    ]
