# Generated by Django 3.1.3 on 2020-11-07 03:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategies', '0005_auto_20201105_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicoption',
            old_name='count',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='basicoption',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basicoption',
            name='status',
            field=models.CharField(choices=[('expired', 'Expired'), ('closed', 'Closed'), ('open', 'Open'), ('exercised', 'Exercised')], default='open', max_length=9),
        ),
    ]
