# Generated by Django 3.1.3 on 2020-11-07 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategies', '0007_auto_20201106_1952'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpreadOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=5)),
                ('open_date', models.DateField()),
                ('close_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField()),
                ('creditdebit', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], default='debit', max_length=6)),
                ('callput', models.CharField(choices=[('call', 'Call'), ('put', 'Put')], default='call', max_length=4)),
                ('strike1', models.DecimalField(decimal_places=2, max_digits=10)),
                ('strike2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('expired', 'Expired'), ('closed', 'Closed'), ('open', 'Open'), ('exercised', 'Exercised')], default='open', max_length=9)),
                ('broker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerage.broker')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
