# Generated by Django 3.1.3 on 2020-11-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0009_basicoption_close_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicoption',
            name='profitloss',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
