# Generated by Django 3.1.3 on 2020-11-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0010_basicoption_profitloss'),
    ]

    operations = [
        migrations.AddField(
            model_name='spreadoption',
            name='close_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='spreadoption',
            name='profitloss',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
