# Generated by Django 3.1.3 on 2020-11-19 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0011_auto_20201111_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicoption',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='spreadoption',
            name='fees',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
