# Generated by Django 3.1.3 on 2021-02-09 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0013_auto_20201118_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicoption',
            name='exp_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='basicoption',
            name='open_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='spreadoption',
            name='exp_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='spreadoption',
            name='open_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
