# Generated by Django 3.1.3 on 2021-02-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategies', '0014_auto_20210208_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicoption',
            name='orderId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spreadoption',
            name='orderId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
