# Generated by Django 3.1.3 on 2021-02-28 19:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0006_auto_20210208_2143'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strategies', '0016_auto_20210208_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusip', models.CharField(max_length=15, null=True)),
                ('ticker', models.CharField(max_length=5)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('exp_date', models.DateField(default=datetime.datetime.now)),
                ('longshort', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default=None, max_length=5, null=True)),
                ('callput', models.CharField(choices=[('call', 'Call'), ('put', 'Put')], default=None, max_length=4, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Close'), ('expired', 'Expired')], default='open', max_length=7)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_fees', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('broker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerage.broker')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='spreadoption',
            name='broker',
        ),
        migrations.RemoveField(
            model_name='spreadoption',
            name='user',
        ),
        migrations.DeleteModel(
            name='BasicOption',
        ),
        migrations.DeleteModel(
            name='SpreadOption',
        ),
    ]
