# Generated by Django 3.1.3 on 2020-11-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='open_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
