# Generated by Django 3.1.3 on 2020-11-18 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0002_broker_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='broker',
            field=models.CharField(choices=[('TD', 'TD Ameritrade'), ('RH', 'Robinhood')], default='RH', max_length=15),
        ),
    ]
