# Generated by Django 3.1.3 on 2021-02-09 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokerage', '0005_auto_20210208_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='broker',
            old_name='account_number',
            new_name='account_id',
        ),
    ]
